### ISSUE TITLE
Mempool transactions are not returned by Zebrad in Regtest mode.

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#144]
```
$ cargo nextest run monitor_unverified_mempool --no-capture
   Compiling integration-tests v0.0.0 (/home/idky137/src/zaino/integration-tests)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 12.90s
    Starting 2 tests across 9 binaries (69 skipped)
       START             integration-tests::wallet_to_validator wallet_basic::zcashd_monitor_unverified_mempool

running 1 test
Checking connection with node..
Connected to node using IPv4 at address http://127.0.0.1:22725/.
Launching Server!

Launching TcpIngestor..
TcpIngestor listening at: 127.0.0.1:16936.
Launching WorkerPool..
Server Ready.
Zaino listening on port Some(16936).
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_block_range.
[TEST] Fetching blocks in range: 1-2.
[TEST] Requests in Queue: 1
[TEST] Requests in Queue: 2
[TEST] Requests in Queue: 1
[TEST] Received call of get_tree_state.
[TEST] Received call of get_transaction.
[TEST] Received call of get_taddress_txids.
[TEST] Requests in Queue: 1
[TEST] Received call of get_transaction.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of send_transaction.
        SLOW [> 60.000s] integration-tests::wallet_to_validator wallet_basic::zcashd_monitor_unverified_mempool
test wallet_basic::zcashd_monitor_unverified_mempool has been running for over 60 seconds
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of send_transaction.


Starting Mempool!

[TEST] Requests in Queue: 1
[TEST] Received call of get_mempool_stream.
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c8000000002b000000000000024fa889f1104028766824c8c03e31ec2b88087d52566c4343bb4438dd4035d0eafde0a975e95b7899ac9f7001dbc2dceab2d5632bcd4c78db3cb2b6597a4b1c2485b36d3b647403908a368f95e35de475891a54494ef0aa1899c9de0ef9916c33c1c57e9a465ff59879aebb7d0412540dbb2c4a84c9d0977bba03f2177f499a815f0c00347fa0353c626ba740f94ec2105baeb0906f5a3b0eb1341e3b1beacfd8f6921446679a64b1e0890479e4decf5e15e0d036731ab606a6c4c31e2354ae85a7ec1ac87caca2ecbfc0f7a116e8065211cd2cff816358ce7f01e0f642ea1fb81989...4aa5ae6ead42f672073551255ce486f2b2ca4aa5f3f10d8252a0180e9745982f79b83b81c57263c4fca6deaa3640430bb4da116c8e686eb483dfd1dd96a592dfe18fc4a7600dfaddf9c78b576ed945fc0e887c7419bc2e75e916bcc6882a87df620fad868818b73dc4148cb9dceddf78bf370a85a9da3ae4c16c3f3489a695c2267592f34cb894d8bf1c70d8e22857ff2c6384ad759fe557c31f651361d5eec5341ed5be67ccffbfc84d201d14e7826380d47cc5fdb04e2b33a6547cc0101fe21896e1d959fdf814a7353f9833870f5884f5a3767c2dbb4fabebab846814082b5a57351a974f0c5359cc88348bd71cbf1eec1ae2d6383df6808",
            ),
        ),
        height: -1,
        confirmations: 0,
    },
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c8000000002b00000000000000021be86fd5068caa8c72a395586aa09e29b735ca0d04e17e5c381068b4d46a59bcc54cc5808a69bf8f13277fde489485d29383cfbac8684981ce24e631a53a803ab65f24477e5aa7cc7c3edf5f2ed13c725b879c96d7b5fe0694a722904ca1812264ed0400cce4439804e41483237c6b1fed01d57ed21ae2afe02460785777a11e363b694872b950b02553d9256a20cb0b69f50838317bb64153d56ea9891b3aa1271118dc11b76c2f2cacc0a1479f162caedfe92c5684c3c273238073d85e5bc4bf2fb5f239e8ce3d9f2406707cfac545dc642aa211dc270089a7f0ba01dd3d8ec0...b513425a5427d0539dcefa7fccd99f0c83d456cdae64338e70beead72289854a56d17cdd96de52e9876a441b3235aa9f90189f367ad15dc9a2011f62003e1c6e97c9da8a88c3b3653b9110ac3b96ecabb9f3cb7aff6dfff263e4b180e433bf28da467b12294a2bde4501a22d18e8fe4b89c7b58443002895c0e218a4d13c2d8777ebd0aabe258c812864495b5fd9cbd7466eac8511aca7fb53eeb811fa8ea210cc943102aba974723e4637029e0c6ab97d29790a9ac4123e336b54cb70b3c3440c28b0c618219b3089d49199ab277a5d64158ced110a025d095ea90bf82e1e705cff9d8859b03063cca033862440dd8bb657edda169be2d651f",
            ),
        ),
        height: -1,
        confirmations: 0,
    },
)


Fetching Raw Mempool!

^[[integration-tests/tests/wallet_to_validator.rs:459:9] txid_1 = NonEmpty {
    head: TxId(
        "67ae651bf9af9635d239b2486341be04709c15a96a9cdd274a750ed94eaad01d",
    ),
    tail: [],
}
[integration-tests/tests/wallet_to_validator.rs:460:9] txid_2 = NonEmpty {
    head: TxId(
        "0126c50e94cef94259ccbb341899a6c0192e04c1adfd440ff4913b1b99d22285",
    ),
    tail: [],
}
[integration-tests/tests/wallet_to_validator.rs:461:9] mempool_txids.clone() = TxidsResponse {
    transactions: [
        "0126c50e94cef94259ccbb341899a6c0192e04c1adfd440ff4913b1b99d22285",
        "67ae651bf9af9635d239b2486341be04709c15a96a9cdd274a750ed94eaad01d",
    ],
}


Fetching Mempool Tx 1!

[integration-tests/tests/wallet_to_validator.rs:464:30] fetch_service.get_raw_transaction(mempool_txids.transactions[0].clone(),
Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c8000000002b000000000000024fa889f1104028766824c8c03e31ec2b88087d52566c4343bb4438dd4035d0eafde0a975e95b7899ac9f7001dbc2dceab2d5632bcd4c78db3cb2b6597a4b1c2485b36d3b647403908a368f95e35de475891a54494ef0aa1899c9de0ef9916c33c1c57e9a465ff59879aebb7d0412540dbb2c4a84c9d0977bba03f2177f499a815f0c00347fa0353c626ba740f94ec2105baeb0906f5a3b0eb1341e3b1beacfd8f6921446679a64b1e0890479e4decf5e15e0d036731ab606a6c4c31e2354ae85a7ec1ac87caca2ecbfc0f7a116e8065211cd2cff816358ce7f01e0f642ea1fb81989...4aa5ae6ead42f672073551255ce486f2b2ca4aa5f3f10d8252a0180e9745982f79b83b81c57263c4fca6deaa3640430bb4da116c8e686eb483dfd1dd96a592dfe18fc4a7600dfaddf9c78b576ed945fc0e887c7419bc2e75e916bcc6882a87df620fad868818b73dc4148cb9dceddf78bf370a85a9da3ae4c16c3f3489a695c2267592f34cb894d8bf1c70d8e22857ff2c6384ad759fe557c31f651361d5eec5341ed5be67ccffbfc84d201d14e7826380d47cc5fdb04e2b33a6547cc0101fe21896e1d959fdf814a7353f9833870f5884f5a3767c2dbb4fabebab846814082b5a57351a974f0c5359cc88348bd71cbf1eec1ae2d6383df6808",
            ),
        ),
        height: -1,
        confirmations: 0,
    },
)


Fetching Mempool Tx 2!

[integration-tests/tests/wallet_to_validator.rs:471:30] fetch_service.get_raw_transaction(mempool_txids.transactions[1].clone(),
Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c8000000002b00000000000000021be86fd5068caa8c72a395586aa09e29b735ca0d04e17e5c381068b4d46a59bcc54cc5808a69bf8f13277fde489485d29383cfbac8684981ce24e631a53a803ab65f24477e5aa7cc7c3edf5f2ed13c725b879c96d7b5fe0694a722904ca1812264ed0400cce4439804e41483237c6b1fed01d57ed21ae2afe02460785777a11e363b694872b950b02553d9256a20cb0b69f50838317bb64153d56ea9891b3aa1271118dc11b76c2f2cacc0a1479f162caedfe92c5684c3c273238073d85e5bc4bf2fb5f239e8ce3d9f2406707cfac545dc642aa211dc270089a7f0ba01dd3d8ec0...b513425a5427d0539dcefa7fccd99f0c83d456cdae64338e70beead72289854a56d17cdd96de52e9876a441b3235aa9f90189f367ad15dc9a2011f62003e1c6e97c9da8a88c3b3653b9110ac3b96ecabb9f3cb7aff6dfff263e4b180e433bf28da467b12294a2bde4501a22d18e8fe4b89c7b58443002895c0e218a4d13c2d8777ebd0aabe258c812864495b5fd9cbd7466eac8511aca7fb53eeb811fa8ea210cc943102aba974723e4637029e0c6ab97d29790a9ac4123e336b54cb70b3c3440c28b0c618219b3089d49199ab277a5d64158ced110a025d095ea90bf82e1e705cff9d8859b03063cca033862440dd8bb657edda169be2d651f",
            ),
        ),
        height: -1,
        confirmations: 0,
    },
)
^[

Fetching Mined Tx 1!

[integration-tests/tests/wallet_to_validator.rs:480:30] fetch_service.get_raw_transaction(mempool_txids.transactions[0].clone(),
Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c8000000002b000000000000024fa889f1104028766824c8c03e31ec2b88087d52566c4343bb4438dd4035d0eafde0a975e95b7899ac9f7001dbc2dceab2d5632bcd4c78db3cb2b6597a4b1c2485b36d3b647403908a368f95e35de475891a54494ef0aa1899c9de0ef9916c33c1c57e9a465ff59879aebb7d0412540dbb2c4a84c9d0977bba03f2177f499a815f0c00347fa0353c626ba740f94ec2105baeb0906f5a3b0eb1341e3b1beacfd8f6921446679a64b1e0890479e4decf5e15e0d036731ab606a6c4c31e2354ae85a7ec1ac87caca2ecbfc0f7a116e8065211cd2cff816358ce7f01e0f642ea1fb81989...4aa5ae6ead42f672073551255ce486f2b2ca4aa5f3f10d8252a0180e9745982f79b83b81c57263c4fca6deaa3640430bb4da116c8e686eb483dfd1dd96a592dfe18fc4a7600dfaddf9c78b576ed945fc0e887c7419bc2e75e916bcc6882a87df620fad868818b73dc4148cb9dceddf78bf370a85a9da3ae4c16c3f3489a695c2267592f34cb894d8bf1c70d8e22857ff2c6384ad759fe557c31f651361d5eec5341ed5be67ccffbfc84d201d14e7826380d47cc5fdb04e2b33a6547cc0101fe21896e1d959fdf814a7353f9833870f5884f5a3767c2dbb4fabebab846814082b5a57351a974f0c5359cc88348bd71cbf1eec1ae2d6383df6808",
            ),
        ),
        height: 3,
        confirmations: 1,
    },
)


Fetching Mined Tx 2!

[TEST] Requests in Queue: 1
[integration-tests/tests/wallet_to_validator.rs:487:30] fetch_service.get_raw_transaction(mempool_txids.transactions[1].clone(),
Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c8000000002b00000000000000021be86fd5068caa8c72a395586aa09e29b735ca0d04e17e5c381068b4d46a59bcc54cc5808a69bf8f13277fde489485d29383cfbac8684981ce24e631a53a803ab65f24477e5aa7cc7c3edf5f2ed13c725b879c96d7b5fe0694a722904ca1812264ed0400cce4439804e41483237c6b1fed01d57ed21ae2afe02460785777a11e363b694872b950b02553d9256a20cb0b69f50838317bb64153d56ea9891b3aa1271118dc11b76c2f2cacc0a1479f162caedfe92c5684c3c273238073d85e5bc4bf2fb5f239e8ce3d9f2406707cfac545dc642aa211dc270089a7f0ba01dd3d8ec0...b513425a5427d0539dcefa7fccd99f0c83d456cdae64338e70beead72289854a56d17cdd96de52e9876a441b3235aa9f90189f367ad15dc9a2011f62003e1c6e97c9da8a88c3b3653b9110ac3b96ecabb9f3cb7aff6dfff263e4b180e433bf28da467b12294a2bde4501a22d18e8fe4b89c7b58443002895c0e218a4d13c2d8777ebd0aabe258c812864495b5fd9cbd7466eac8511aca7fb53eeb811fa8ea210cc943102aba974723e4637029e0c6ab97d29790a9ac4123e336b54cb70b3c3440c28b0c618219b3089d49199ab277a5d64158ced110a025d095ea90bf82e1e705cff9d8859b03063cca033862440dd8bb657edda169be2d651f",
            ),
        ),
        height: 3,
        confirmations: 1,
    },
)
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_block_range.
[TEST] Fetching blocks in range: 1-4.
[TEST] Requests in Queue: 1
[TEST] Requests in Queue: 2
[TEST] Requests in Queue: 3
[TEST] Received call of get_taddress_txids.
[TEST] Received call of get_tree_state.
[TEST] Received call of get_tree_state.
[TEST] Requests in Queue: 1
[TEST] Received call of get_transaction.
[TEST] Requests in Queue: 1
[TEST] Received call of get_transaction.
[TEST] Requests in Queue: 1
[TEST] Requests in Queue: 2
[TEST] Received call of get_mempool_stream.
[TEST] Received call of get_latest_block.
test wallet_basic::zcashd_monitor_unverified_mempool ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 13 filtered out; finished in 91.02s

        PASS [  91.049s] integration-tests::wallet_to_validator wallet_basic::zcashd_monitor_unverified_mempool
       START             integration-tests::wallet_to_validator wallet_basic::zebrad_monitor_unverified_mempool

running 1 test
Checking connection with node..
Connected to node using IPv4 at address http://127.0.0.1:23299/.
Launching Server!

Launching TcpIngestor..
TcpIngestor listening at: 127.0.0.1:21245.
Launching WorkerPool..
Server Ready.

Launching TcpIngestor..
TcpIngestor listening at: 127.0.0.1:21245.
Launching WorkerPool..
Server Ready.
Zaino listening on port Some(21245).
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_block_range.
[TEST] Fetching blocks in range: 1-2.
[TEST] Requests in Queue: 1
[TEST] Received call of get_taddress_txids.
[TEST] Requests in Queue: 1
[TEST] Received call of get_tree_state.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_block_range.
[TEST] Fetching blocks in range: 3-102.
[TEST] Requests in Queue: 1
[TEST] Received call of get_taddress_txids.
        SLOW [> 60.000s] integration-tests::wallet_to_validator wallet_basic::zebrad_monitor_unverified_mempool
test wallet_basic::zebrad_monitor_unverified_mempool has been running for over 60 seconds
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of send_transaction.
[TEST] Requests in Queue: 1
[TEST] Received call of get_tree_state.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_block_range.
[TEST] Fetching blocks in range: 103-202.
[TEST] Requests in Queue: 1
[TEST] Requests in Queue: 1
[TEST] Received call of get_tree_state.
[TEST] Received call of get_taddress_txids.
[TEST] Requests in Queue: 1
[TEST] Received call of get_transaction.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of send_transaction.
[TEST] Requests in Queue: 1
[TEST] Received call of get_tree_state.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_block_range.
[TEST] Fetching blocks in range: 203-203.
[TEST] Requests in Queue: 1
[TEST] Requests in Queue: 2
[TEST] Received call of get_tree_state.
[TEST] Received call of get_taddress_txids.
[TEST] Requests in Queue: 1
[TEST] Received call of get_transaction.
        SLOW [>120.000s] integration-tests::wallet_to_validator wallet_basic::zebrad_monitor_unverified_mempool
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of send_transaction.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of get_latest_block.
[TEST] Requests in Queue: 1
[TEST] Received call of send_transaction.


Starting Mempool!

[TEST] Requests in Queue: 1
[TEST] Received call of get_mempool_stream.
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 18374),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
        SLOW [>180.000s] integration-tests::wallet_to_validator wallet_basic::zebrad_monitor_unverified_mempool
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[TEST] Requests in Queue: 1
[TEST] Received call of get_mempool_stream.
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 18374),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22311),
    ),
)
[zaino-serve/src/rpc/service.rs:1291:43] zebrad_client.get_raw_transaction(txid.clone(), Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)


Fetching Raw Mempool!

[integration-tests/tests/wallet_to_validator.rs:459:9] txid_1 = NonEmpty {
    head: TxId(
        "7b3abfdd08c4e8b858d4adbedeae6046e3586a43b80f62e155616b792ea70bdb",
    ),
    tail: [],
}
[integration-tests/tests/wallet_to_validator.rs:460:9] txid_2 = NonEmpty {
    head: TxId(
        "4c49cc6762ba009b10b2e5f97d54bb48bf71df8bef4c216922faa76b2d1acf60",
    ),
    tail: [],
}
[integration-tests/tests/wallet_to_validator.rs:461:9] mempool_txids.clone() = TxidsResponse {
    transactions: [
        "4c49cc6762ba009b10b2e5f97d54bb48bf71df8bef4c216922faa76b2d1acf60",
        "7b3abfdd08c4e8b858d4adbedeae6046e3586a43b80f62e155616b792ea70bdb",
    ],
}


Fetching Mempool Tx 1!

[integration-tests/tests/wallet_to_validator.rs:464:30] fetch_service.get_raw_transaction(mempool_txids.transactions[0].clone(),
Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 22310),
    ),
)


Fetching Mempool Tx 2!

[integration-tests/tests/wallet_to_validator.rs:471:30] fetch_service.get_raw_transaction(mempool_txids.transactions[1].clone(),
Some(1)).await = Err(
    SerdeJsonError(
        Error("expected a hex string", line: 1, column: 18374),
    ),
)


Fetching Mined Tx 1!

[integration-tests/tests/wallet_to_validator.rs:480:30] fetch_service.get_raw_transaction(mempool_txids.transactions[0].clone(),
Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c800000000f400000000000002599e86b0f13337fe504e4510a4f3969c65a9978e1f7b3b21fca1673e774ee101b54354a5f47aae67f207bcabba5f9aacebe8f33f1a85b8f0af84a52f86b8d8119a64f62e6b23ed278d9af296a193ce33b501e5165f21e5d0e739799d072fa2d0601646c95428497bf8d505dc84b86ff8129b177a32e4f1bfb4533e8744fc631810d20d8aeff976af5bab54408d118781614a81f1c1af6bcc7aad091f46535fad8884ebe4a3051a421507274c2ac6e0b1b216fab9b8447270188b2247cba9892a1b24dfa565082f987df3fa92487073db8593555053fc5b2c8a984d4fe2f9f7c6e889...aa59849b12ebe019700bcccc9cab71084c561fed18ac961ad07ed5678aef7e46248d4521d28241fe393c39fe08a378f101e74db1a5f2e6b3313e2d548848b769bee2040f15b309d62376254f7f1d6638c5cd5df62c45423fa9c3639dafea9a6194cb27a70e15f9f4315c07d422a57b62b717fdd8ca80b3f153730f401658959af9305c0822bc794287b6532067c29c197638f9c9766298f252afb4695430d86f5dad05f071f1004ed47cc45ce3fa531b9c26ec8cee2e053582f871b6f4568c7acfe8660fdd4d7769d5c402fdd96032b393cad22f632c4bd3d1ab56d410cd9b2f74833e9478ede2ec05f6ba5d9d23fa3ed4236a7b01f6c41110a",
            ),
        ),
        height: 204,
        confirmations: 1,
    },
)


Fetching Mined Tx 2!

[integration-tests/tests/wallet_to_validator.rs:487:30] fetch_service.get_raw_transaction(mempool_txids.transactions[1].clone(),
Some(1)).await = Ok(
    Object {
        hex: SerializedTransaction(
            SerializedTransaction(
                "050000800a27a7265510e7c800000000f40000000000000002f520a52ade8213a3d6d372757b902f036cd35c0a328bcf4db3d385af7d30db80ac648c20f5e8b25329e270b5e8deb003c07c5fe58bbe046311ec4d7f09481d00b969f89586ad5b34699675ba43e204f21ae4571d1f6813744c0ad0a41f3235ac83d1664a564fb2fb50dea386ae4702957acefba2401f56d6a56a876e56f5842f9106a3d1556e344ca90ac2c12d88e505417bbe002f21811b8c509bc2fcb93893310632c1846cf347b0f94003dd0e8efce8cad0a2c02fbd05d0973414b79acaa827c8a785f5e718123c2bef74b8cefa9c50505541209b9c25098be4e708452acb71...d74e31bc084a06ec2bb4b14caeb5d9e79007e49385b23a1a92108407ad51a92da4ea87380ead174631e6360ff68fe9565d17a67ccdcb8f1d5110d3d3b5f72487d5a9a8cfc53750fa3ada3a2d4dfdbbf27ef291669e0ee0b72a3064da9ddefc57a12e1612d745388e0640888b2eff4159431ef2a17e547f43c154de7689c148ce6fe83a85d8fd8181f6c2de4c4001effabd00f51c06d45d44b221c43537cc1ded4ad98dd46b74bcdd0d35692fc497216dd035316346b13e56612b6f6a18a4f705fe548c9eca709b6ab00977a9281330e24462dd2ee46bb7ced14ce6b311260b816d233ff537082a2cbd14c59c5982782f35c07c80897f11fc23e",
            ),
        ),
        height: 204,
        confirmations: 1,
    },
)
thread 'wallet_basic::zebrad_monitor_unverified_mempool' panicked at integration-tests/tests/wallet_to_validator.rs:493:9:
assertion `left == right` failed
  left: 0
 right: 250000
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:410:17
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: wallet_to_validator::wallet_basic::monitor_unverified_mempool::{{closure}}
             at ./tests/wallet_to_validator.rs:493:9
   5: wallet_to_validator::wallet_basic::zebrad_monitor_unverified_mempool::{{closure}}
             at ./tests/wallet_to_validator.rs:384:46
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:729:57
   9: tokio::runtime::coop::with_budget
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:107:5
  10: tokio::runtime::coop::budget
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:73:5
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:729:25
  12: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:428:19
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:728:36
  14: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:807:68
  15: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/scoped.rs:40:9
  16: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context.rs:180:26
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:283:12
  18: std::thread::local::LocalKey<T>::with
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:260:9
  19: tokio::runtime::context::set_scheduler
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context.rs:180:9
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:807:27
  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:716:19
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:196:28
  23: tokio::runtime::context::runtime::enter_runtime
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/runtime.rs:65:16
  24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:184:9
  25: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:368:47
               26: tokio::runtime::runtime::Runtime::block_on
             at /home/idky137/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:342:13
  27: wallet_to_validator::wallet_basic::zebrad_monitor_unverified_mempool
             at ./tests/wallet_to_validator.rs:384:9
  28: wallet_to_validator::wallet_basic::zebrad_monitor_unverified_mempool::{{closure}}
             at ./tests/wallet_to_validator.rs:383:49
  29: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test wallet_basic::zebrad_monitor_unverified_mempool ... FAILED

failures:

failures:
    wallet_basic::zebrad_monitor_unverified_mempool

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 13 filtered out; finished in 184.32s

        FAIL [ 184.351s] integration-tests::wallet_to_validator wallet_basic::zebrad_monitor_unverified_mempool
------------
     Summary [ 275.400s] 2 tests run: 1 passed (1 slow), 1 failed, 69 skipped
        FAIL [ 184.351s] integration-tests::wallet_to_validator wallet_basic::zebrad_monitor_unverified_mempool
error: test run failed
```

**Comment by idky137** [comment]
- Relevant tests is in https://github.com/zingolabs/zaino/pull/140

**Comment by idky137** [comment]
This was dues to a change in zebra's transaction response. 

Where zcashd uses a signed int for transaction height and returns -1 for mempool transactions. Zebrad now uses an Option<u32> for height and returns None for mempool transactions. Deserialisation for transaction responses has been fixed in #153. merging that PR will close this issue.
